### ISSUE TITLE
 (node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/generator-loopback#89] opened 2015-02-20 20:01 UTC
Enter an empty property name when done.
    ? Property name: dose_man_hour
       invoke   loopback:property
    ? Property type: number
    ? Required? Yes
    
    Let's add another SubActivity property.
    Enter an empty property name when done.
    ? Property name: dose_man_day
       invoke   loopback:property
    ? Property type: number
    ? Required? Yes
    
    Let's add another SubActivity property.
    Enter an empty property name when done.
    ? Property name: norm_man_hour
       invoke   loopback:property
    (node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
    Trace
        at addListener (events.js:179:15)
        at run (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:444:21)
        at invoke (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/generator-loopback/node_modules/yeoman-generator/lib/actions/invoke.js:38:20)
        at null.<anonymous> (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/generator-loopback/model/index.js:176:12)
        at null.<anonymous> (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:221:7)
        at PromptUI.onCompletion (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
        at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1929:12)
        at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
        at AutoDetachObserverPrototype.completed (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:4604:23)
        at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/paulomcnally/.nvm/v0.12.0/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    ? Property type: (Use arrow keys)
    ❯ string 
      number 
      boolean 
      object 
      array 
      date 

I only added multiples properties to a model.

**Comment by bajtos** [comment] 2015-03-04 07:57
Possibly a duplicate of #92

**Comment by Amir-61** [comment] 2015-11-18 20:54
Possibly duplicate of https://github.com/strongloop/loopback/issues/404; we close this.

**Closed** 2015-11-18 20:55 UTC
Labels: duplicate, triage
