### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb acl in command line in RUS locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#378] opened 2018-08-16 11:55 UTC
Test Case: 11.020.060

Issue: English string occurs when input lb acl in command line

![image](https://user-images.githubusercontent.com/34856053/44206982-1dab6580-a18e-11e8-99c2-2de4820bd643.png)
![image](https://user-images.githubusercontent.com/34856053/44206994-2d2aae80-a18e-11e8-918f-ad95dce27ff6.png)
![image](https://user-images.githubusercontent.com/34856053/44207009-361b8000-a18e-11e8-9efb-a929467a822a.png)
![image](https://user-images.githubusercontent.com/34856053/44207018-3ddb2480-a18e-11e8-8701-15fb59d1bd17.png)

**Comment by dhmlau** [comment] 2018-08-17 19:52
It seems to be working fine for me. Please see the screen caps below.  We just released 

<img width="391" alt="2018-08-17 3 43 33" src="https://user-images.githubusercontent.com/25489897/44285920-22772480-a235-11e8-91f4-5a02afd0256a.png">
<img width="531" alt="2018-08-17 3 43 46" src="https://user-images.githubusercontent.com/25489897/44285923-2440e800-a235-11e8-9fae-8252171d63ab.png">
<img width="544" alt="2018-08-17 3 43 54" src="https://user-images.githubusercontent.com/25489897/44285927-26a34200-a235-11e8-8096-aaa64f02bedc.png">
<img width="538" alt="2018-08-17 3 44 04" src="https://user-images.githubusercontent.com/25489897/44285929-286d0580-a235-11e8-8549-6864a40d7cd5.png">
<img width="555" alt="2018-08-17 3 44 10" src="https://user-images.githubusercontent.com/25489897/44285930-299e3280-a235-11e8-8a86-fb7a2cd4abeb.png">

The `other` in the 4th screen cap should be translated but it is covered in https://github.com/strongloop/generator-loopback/issues/368.  

Could you please verify with the latest version of generator-loopback@5.9.0 and loopback-workspace@4.3.1?

**Comment by gongkegongke** [comment] 2018-08-20 02:27
I just verified on latest build, some strings are translated now, but there are still 2 strings that are not translated, please help to check.

![image](https://user-images.githubusercontent.com/34856053/44317373-76ffe700-a463-11e8-8506-4e64bba86b08.png)
![image](https://user-images.githubusercontent.com/34856053/44317386-897a2080-a463-11e8-9985-76acbff0ae63.png)

**Comment by dhmlau** [comment] 2018-08-20 13:35
@gongkegongke , it's covered in https://github.com/strongloop/generator-loopback/issues/368.  Both will be fixed in this PR: https://github.com/strongloop/generator-loopback/pull/381.

**Comment by dhmlau** [comment] 2018-08-20 13:36
Since this issue is not specific to RUS and already covered in #368 , I'm closing this as duplicate of #368.

**Closed** 2018-08-20 13:39 UTC
Labels: GVT
