### ISSUE TITLE
Fix the skipped test cases after upgrading to yeoman-generator@3.x

### ISSUE THREAD

**Issue by jannyHou** [strongloop/generator-loopback#389] opened 2018-08-28 20:11 UTC
# Description/Steps to reproduce

A follow up issue of https://github.com/strongloop/generator-loopback/pull/363
Fix the 2 skipped tests in `datasource.test.js`

# Expected result

The 2 skipped tests pass

**Comment by dhmlau** [comment] 2018-10-23 17:10
@jannyHou , after all the tests passed in `generator-loopback`, any outstanding tasks need to be done in order to release a semver-major version of `loopback-cli` to make use of the new `generator-loopback`?

**Comment by jannyHou** [comment] 2018-10-23 18:16
@dhmlau I would say this task shouldn't block the semver-major release of `loopback-cli`.

**Comment by bajtos** [comment] 2019-02-08 14:58
This task has been sitting in backlog for ~6 months by now and there was no problem (regression) caused by the fact that we are skipping some of the tests. Considering how little changes we are making in generator-loopback anyways, I am proposing to close this issue as "wontfix".

@jannyHou thoughts?

**Comment by jannyHou** [comment] 2019-02-11 18:45
I manually verified those two commands work on local, the time was spent on figuring out how to use yeoman-test functions(haven't found a good solution yet). 
I am good to close it.

**Comment by dhmlau** [comment] 2019-02-11 19:51
Closing per [above comment](https://github.com/strongloop/generator-loopback/issues/389#issuecomment-461829478).

**Closed by dhmlau** 2019-02-11 19:51 UTC
Labels: TOB
