### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#365] opened 2018-08-14 08:30 UTC
Test Case: 11.020.030

![image](https://user-images.githubusercontent.com/34856053/44080566-00d43992-9fdf-11e8-860b-e9f81faf0f6e.png)
![image](https://user-images.githubusercontent.com/34856053/44080523-dd91dcdc-9fde-11e8-9d81-24ee74a29a30.png)
![image](https://user-images.githubusercontent.com/34856053/44080541-eaaf7ffa-9fde-11e8-9534-e7df16766a34.png)

Issue: English string occurs when input **lb** in command line

**Comment by dhmlau** [comment] 2018-08-17 13:34
Closing as duplicate of https://github.com/strongloop/generator-loopback/issues/369
The description of the application kind should be translated in the latest release of `loopback-workspace@4.3.1`.  Please also see my comment in https://github.com/strongloop/generator-loopback/issues/369#issuecomment-413564943.

**Closed by dhmlau** 2018-08-17 13:34 UTC
