### ISSUE TITLE
loopback:datasource not work for remote datasource

### ISSUE THREAD

**Issue by a136464153** [strongloop/generator-loopback#201] opened 2016-06-10 05:31 UTC
![image](https://cloud.githubusercontent.com/assets/6264919/15954947/65aa45b6-2f0f-11e6-81fa-281536fe495c.png)
When generate remote datasource by slc loopback:datasource, I select other and type remote, it shows error.I reinstalled strongloop and it does not work.

**Comment by 0candy** [comment] 2016-07-06 18:27
Duplicate of https://github.com/strongloop/loopback/issues/2265

This has been fixed in `generator-loopback@1.22.0`.

**Closed by 0candy** 2016-07-06 18:27 UTC
Labels: duplicate, triage
