### ISSUE TITLE
lb relation command stuck at first model selection

### ISSUE THREAD

**Issue by ajsnyman** [strongloop/generator-loopback#296] opened 2017-06-27 20:15 UTC
# Description/Steps to reproduce

> 
**$ lb relation**
? Select the model to create the relationship from:
>

Selection is stuck at first model, even though other models are displayed and visible.
I'm unable to select any of the other models below with the down arrow.

I'm running lb on Windows 10 in command prompt.

# Expected result

Should be able to select other model.

**Comment by raymondfeng** [comment] 2017-06-27 23:37
There is a bug in Node 8.1.0. Upgrading to 8.1.1 or 8.1.2 should fix the issue.

**Comment by raymondfeng** [comment] 2017-06-27 23:39
Duplicate of https://github.com/strongloop/loopback-cli/issues/36

**Closed by raymondfeng** 2017-06-27 23:39 UTC
