### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb app in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#369] opened 2018-08-14 08:44 UTC
Test Case: 11.020.070

![image](https://user-images.githubusercontent.com/34856053/44081392-2f97498e-9fe1-11e8-9921-bb1c6de7a20b.png)
![image](https://user-images.githubusercontent.com/34856053/44081411-382e0484-9fe1-11e8-95c7-1113a63c24ae.png)

Issue: English string occurs when input **lb app** in command line

**Comment by dhmlau** [comment] 2018-08-16 00:43
Text in the first and third highlighted box is coming from Yeoman, one of our dependencies.  This is not something we can fix.  
For the 2nd box, the names of the application kind are not meant to be translated. However the description should be translated.  We got the translation files 3 days ago and just released `loopback-workspace@4.3.1`.  Could you please try again?  You should see the description being translated.  Thanks.

**Comment by gongkegongke** [comment] 2018-08-16 11:59
I tried the build with RUS locale, the issue still exists

![image](https://user-images.githubusercontent.com/34856053/44207195-e38e9380-a18e-11e8-8771-35e4231d4555.png)

**Comment by dhmlau** [comment] 2018-08-16 14:27
The screen cap from https://github.com/strongloop/generator-loopback/issues/369#issuecomment-413521226 is showing the expected behavior.  As mentioned [above](https://github.com/strongloop/generator-loopback/issues/369#issuecomment-413384927), this is coming from Yeoman and not something we can fix. 

The one that it should be translated is the description of the application kind, which it is. 
<img width="509" alt="2018-08-16 10 24 59" src="https://user-images.githubusercontent.com/25489897/44214799-f5e0e100-a13e-11e8-832d-7bc9444950fc.png">

**Comment by dhmlau** [comment] 2018-08-17 03:45
With the reasons above, I'd like to close this ticket. Thanks.

**Closed by dhmlau** 2018-08-17 03:45 UTC
