### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input node . in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#367] opened 2018-08-14 08:38 UTC
Test Case: 11.020.050

![image](https://user-images.githubusercontent.com/34856053/44081021-4eec9dc6-9fe0-11e8-81f1-5b464a2a3978.png)

Issue: English string occurs when input **node .** in command line

**Comment by dhmlau** [comment] 2018-08-16 00:30
Closing as duplicate of https://github.com/strongloop/generator-loopback/issues/329

**Closed** 2018-08-16 00:43 UTC
