### ISSUE TITLE
app generator gives Node warning "possible EventEmitter memory leak detected."

### ISSUE THREAD

**Issue by crandmck** [strongloop/generator-loopback#92] opened 2015-02-26 22:48 UTC
Although it's only a warning, it certainly doesn't give a great first impression for someone just creating the sample app.
```
$ slc --version
strongloop v2.10.3 (node v0.10.36)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├─┬ strong-supervisor@1.4.1 (c945bd1)
│ └── strong-agent@1.3.2
├── node-inspector@0.7.4
├── strong-deploy@1.1.4 (5e25e21)
├── strong-pm@1.7.2 (315d448)
├── strong-registry@1.1.4 (aab3dbb)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.2 (96a7f70)
```

```
$ slc loopback:example
...
Create initial project scaffolding
Add datasource geo
Add model Car
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:160:15)
    at run (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:444:21)
    at module.exports.yeoman.generators.Base.extend._runGeneratorWithAnswers (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/example/index.js:621:22)
    at module.exports.yeoman.generators.Base.extend._createProperty (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/example/index.js:524:10)
    at /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/example/index.js:482:16
    at iterate (/usr/local/lib/node_modules/strongloop/node_modules/async/lib/async.js:149:13)
    at /usr/local/lib/node_modules/strongloop/node_modules/async/lib/async.js:160:25
    at setExtraOptions (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/example/index.js:541:40)
    at null.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:382:5)
    at Queue.g (events.js:180:16)
```

**Comment by rmg** [comment] 2015-02-26 23:32
@raymondfeng @bajtos similar to strongloop/loopback#404?

Seems to pop up occassionally in yeoman land:
 * yeoman/generator#641
 * yeoman/yo#64

**Comment by bajtos** [comment] 2015-02-27 09:13
Perhaps @superkhau can take a look?

**Comment by superkhau** [comment] 2015-02-27 22:13
Sure. @chandadharap Can you prioritize this on waffle? TY.

**Comment by superkhau** [comment] 2015-05-12 08:11
@crandmck I believe this is fixed in the latest version of LoopBack. Anyways, run `slc update` and then `slc loopback:example` and let me know if you still see the warnings. For now, I will close this issue as I believe it is resolved.

**Comment by donaldffortin** [comment] 2015-06-19 15:44
strongloop 4.0.4
node 0.12.4
OSX 10.9.5

We just added a model and generated this warning message.  It appears that things still work.  After reviewing the various postings, it seems like we need to place emitter.setMaxListeners(0) somewhere to suppress the message.  What is the emitter in loopback that is causing this warning? Is there an example of how/where to setMaxListeners?  Thanks in advance. 

(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:179:15)
    at DataSource.once (events.js:204:8)
    at DataSource.ready (/Users/dfortin/Downloads/lb_starter/node_modules/loopback-datasource-juggler/lib/datasource.js:2028:8)
    at stillConnecting (/Users/dfortin/Downloads/lb_starter/node_modules/loopback-datasource-juggler/lib/dao.js:324:23)
    at Function.DataAccessObject.create (/Users/dfortin/Downloads/lb_starter/node_modules/loopback-datasource-juggler/lib/dao.js:159:27)
    at /Users/dfortin/Downloads/lb_starter/server/boot/create-sample-model.js:258:21
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/Users/dfortin/Downloads/lb_starter/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DataSource.addListener (events.js:179:15)
    at DataSource.once (events.js:204:8)
    at DataSource.ready (/Users/dfortin/Downloads/lb_starter/node_modules/loopback-datasource-juggler/lib/datasource.js:2029:8)
    at stillConnecting (/Users/dfortin/Downloads/lb_starter/node_modules/loopback-datasource-juggler/lib/dao.js:324:23)
    at Function.DataAccessObject.create (/Users/dfortin/Downloads/lb_starter/node_modules/loopback-datasource-juggler/lib/dao.js:159:27)
    at /Users/dfortin/Downloads/lb_starter/server/boot/create-sample-model.js:258:21
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/Users/dfortin/Downloads/lb_starter/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)

**Comment by bajtos** [comment] 2015-06-19 16:43
Using the 8605c16 and the following dependencies, I am able to reproduce the problem by running `npm test` in the project.

```
$ npm ls --depth 0
generator-loopback@1.10.0 /Users/bajtos/src/loopback/generator-loopback
├── async@0.9.2
├── chai@1.10.0
├── chalk@0.5.1
├── debug@2.2.0
├── fs-extra@0.12.0
├── inflection@1.7.1
├── jshint@2.8.0
├── loopback-swagger@2.0.0
├── loopback-workspace@3.15.0
├── mocha@2.2.5
├── request@2.58.0
├── strong-cached-install@2.0.0
├── yeoman-generator@0.18.10
└── yosay@1.0.4
```

**Comment by superkhau** [comment] 2015-07-07 23:45
@donaldffortin I can't reproduce this. Can you provide the steps to reproduce? My steps are as follows:

```
slc loopback test
cd test
slc loopback:model Truck
# no event emitter warnings
```

@bajtos I tried:

```
slc loopback:example
cd loopback-example-app
npm test
# no event emitter warnings
```

Closing. Reopen if you guys are still running into issues and can provide exact steps to reproduce.

```
slc -v
strongloop v4.0.5 (node v0.10.36)
├── strong-arc@1.6.0 (cfb2378)
├── strong-build@2.0.3 (b66d030)
├── strong-deploy@2.2.2 (13baab4)
├── strong-pm@4.3.1 (45d254a)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.2.0 (e59f8b5)
├─┬ strong-supervisor@2.0.2 (610a578)
│ └── strong-agent@1.6.3
├── generator-loopback@1.10.1 (eae270c)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Closed** 2015-07-07 23:48 UTC
Labels: bug

**Comment by donaldffortin** [comment] 2015-07-08 12:00
As I tried to reproduce the conditions similar to what you have done, I realized that when I reported the issue, I had added the file parameter to datasources.json as shown below.


{

  "db": {

    "name": "db",

    "connector": "memory" ,

   "file":"db.json"

}

}


After I had added the 12th model to our application was when the issue occurred. Removal of the file parameter eliminates the emitter warning.  Sorry about that.


________________________________

**Comment by superkhau** [comment] 2015-07-08 18:18
Interesting, I do not see any event emitter warnings even with the `file` key being set. I didn't add 12 models though. If anyone else reports something more concrete, I will check again. Thanks for the report!

**Comment by rmg** [comment] 2015-07-08 20:06
If it is adding listeners per-model, which seems likely, then that would be the cause. Note that #102 increased the limit to 256, so that would suggest that each model adds more than a few listeners.
